name: apiverve_jsonschemavalidator
description: JSON Schema Validator is a comprehensive tool for validating JSON data against JSON Schema definitions. It provides detailed error reporting with field-level validation results.
version: 1.1.14
homepage: https://apiverve.com/marketplace/jsonschemavalidator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/jsonschemavalidator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
